right_arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 6.920104237897878e-310
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3
left_arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 6.920104237897878e-310
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3